services:
  backend:
    build: .
    container_name: adlip_backend
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongo:27017/adlip
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    volumes:
      - ./app:/usr/src/app/app
      - ./patterns:/patterns
      - ../osint_datasets_files:/usr/src/app/osint_datasets_files

  worker:
    build: .
    container_name: adlip_worker
    command: celery -A app.celery_app:celery worker --loglevel=info
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongo:27017/adlip
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
    depends_on:
      - redis
      - mongo
    volumes:
      - ./app:/usr/src/app/app
      - ./patterns:/patterns
      - ../osint_datasets_files:/usr/src/app/osint_datasets_files


  redis:
    image: redis:7-alpine
    container_name: adlip_redis
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6.0
    container_name: adlip_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: